qpe: Fix compile error
Getting this error

    qpe.c: In function ‘qp_encode’:
    qpe.c:94:2: error: format ‘%d’ expects argument of type ‘int’, but
    argument 5 has type ‘size_t’ [-Werror=format=]
    fprintf(stderr,"%s:%d:DEBUG: Line terminator length = %d", FL,
      strlen(line_terminator));

Use %zu instead of %d for printing size_t (size_t is unsigned).

Signed-off-by: Andrew Clayton <andrew@zeta.digital-domain.net>